### PR TITLE
draw: start drawing ellipses from the center

### PR DESCRIPTION
**Pull request by lelgenio**
The idea behind this is making the ellipse tool more distinct from the rectangle tool
and i don't know if having a modifier key is something that is viable.

I won't get offended if this is not merged ;)

swappy-20210123_144517

### CODE REVIEW

**Comment by jtheoof** [comment]
This would break the existing behaviour. 

I'd rather have it behind a `Shift` modifier key. I think this is how other tools like gimp are doing it.

**Comment by lelgenio** [comment]
For this to work 100% it would be necessary to run `draw_area_motion_notify_handler` on shift down/up, which I was unable to achieve.

**Comment by jtheoof** [comment]
Yes indeed, it looks a bit odd in the current state. The modifier key press/release should re-render the state.
Also I checked how gimp does it, the modifier used for this use-case is `Ctrl` not `Shift` (my bad).

**Comment by lelgenio** [comment]
Other than the documentation, which I'm not 100% sure on, this should be good to go.

**Review by jtheoof — CHANGES_REQUESTED** [review]
The behavior looks OK but there are few things to change. See my comments.

Also, could you please squash all your commits into just one and rebase your changes from my remote `master` branch?

**Review by jtheoof — APPROVED** [review]
Thanks @lelgenio

**Pull request merged**
